# Generated by Django 3.2.9 on 2021-11-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_alter_contato_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='publicar',
            field=models.BooleanField(default=True),
        ),
    ]
